# Generated by Django 2.0.13 on 2019-07-16 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='pubish_date',
            new_name='publish_date',
        ),
    ]
